### ISSUE TITLE
Cancel button is not working after re-entering scene

### ISSUE THREAD

**Issue by marxsk** [lazaronixon/react-native-qrcode-reader#7]
Hi,

I have found out that method for 'Cancel' is called only when scene is entered for the first time. After re-entering (navigator.push) the scene, function is not called after button is pressed.

When the scene is visited for the first time, the function can be executed multiple times without issues.

**Comment by brandonfancher** [comment]
I believe this is happening because the button sometimes renders before the Camera, therefore it is being given a lower "z-index" if you will. It's getting stuck in a layer beneath the Camera, so the Camera intercepts touch gestures and they never reach the button.

My solution was to Move the CancelButton outside of the Camera component, making it a sibling to the Camera Component. Then render it in some whitespace outside of the Camera on the screen, and it works.

Hope this helps.

**Comment by marxsk** [comment]
Thanks for a response, it looks like the problem is in https://github.com/lwansbrough/react-native-camera/issues/323 but fortunately, it does not work only in simulator and it works correctly on a real phone.

**Comment by brandonfancher** [comment]
Hi Mark. Actually, I believe these are two separate issues. I was already aware of issue #323 in react-native-camera and had already worked around that. This issue #7 happened on the real phone for me too. Just saying that here in case anyone runs into this as a separate issue and wants to try my solution.
